/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app/index'
import { Route as AuthenticatedAppBranchesRouteImport } from './routes/_authenticated/app/branches'
import { Route as AuthenticatedAppProductsRouteImport } from './routes/_authenticated/app/products'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app/settings'
import { Route as AuthenticatedAppUsersRouteImport } from './routes/_authenticated/app/users'
import { Route as AuthenticatedAppProductsIndexRouteImport } from './routes/_authenticated/app/products/index'
import { Route as AuthenticatedAppProductsProductIdRouteImport } from './routes/_authenticated/app/products/$productId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppBranchesRoute =
  AuthenticatedAppBranchesRouteImport.update({
    id: '/branches',
    path: '/branches',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProductsRoute =
  AuthenticatedAppProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppUsersRoute = AuthenticatedAppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppProductsIndexRoute =
  AuthenticatedAppProductsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppProductsRoute,
  } as any)
const AuthenticatedAppProductsProductIdRoute =
  AuthenticatedAppProductsProductIdRouteImport.update({
    id: '/$productId',
    path: '/$productId',
    getParentRoute: () => AuthenticatedAppProductsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/branches': typeof AuthenticatedAppBranchesRoute
  '/app/products': typeof AuthenticatedAppProductsRouteWithChildren
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/users': typeof AuthenticatedAppUsersRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/products/$productId': typeof AuthenticatedAppProductsProductIdRoute
  '/app/products/': typeof AuthenticatedAppProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/branches': typeof AuthenticatedAppBranchesRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/users': typeof AuthenticatedAppUsersRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/products/$productId': typeof AuthenticatedAppProductsProductIdRoute
  '/app/products': typeof AuthenticatedAppProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/app/branches': typeof AuthenticatedAppBranchesRoute
  '/_authenticated/app/products': typeof AuthenticatedAppProductsRouteWithChildren
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/app/users': typeof AuthenticatedAppUsersRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/products/$productId': typeof AuthenticatedAppProductsProductIdRoute
  '/_authenticated/app/products/': typeof AuthenticatedAppProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/app'
    | '/app/branches'
    | '/app/products'
    | '/app/settings'
    | '/app/users'
    | '/app/'
    | '/app/products/$productId'
    | '/app/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/branches'
    | '/app/settings'
    | '/app/users'
    | '/app'
    | '/app/products/$productId'
    | '/app/products'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/app'
    | '/_authenticated/app/branches'
    | '/_authenticated/app/products'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/users'
    | '/_authenticated/app/'
    | '/_authenticated/app/products/$productId'
    | '/_authenticated/app/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/branches': {
      id: '/_authenticated/app/branches'
      path: '/branches'
      fullPath: '/app/branches'
      preLoaderRoute: typeof AuthenticatedAppBranchesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/products': {
      id: '/_authenticated/app/products'
      path: '/products'
      fullPath: '/app/products'
      preLoaderRoute: typeof AuthenticatedAppProductsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/users': {
      id: '/_authenticated/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AuthenticatedAppUsersRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/products/': {
      id: '/_authenticated/app/products/'
      path: '/'
      fullPath: '/app/products/'
      preLoaderRoute: typeof AuthenticatedAppProductsIndexRouteImport
      parentRoute: typeof AuthenticatedAppProductsRoute
    }
    '/_authenticated/app/products/$productId': {
      id: '/_authenticated/app/products/$productId'
      path: '/$productId'
      fullPath: '/app/products/$productId'
      preLoaderRoute: typeof AuthenticatedAppProductsProductIdRouteImport
      parentRoute: typeof AuthenticatedAppProductsRoute
    }
  }
}

interface AuthenticatedAppProductsRouteChildren {
  AuthenticatedAppProductsProductIdRoute: typeof AuthenticatedAppProductsProductIdRoute
  AuthenticatedAppProductsIndexRoute: typeof AuthenticatedAppProductsIndexRoute
}

const AuthenticatedAppProductsRouteChildren: AuthenticatedAppProductsRouteChildren =
  {
    AuthenticatedAppProductsProductIdRoute:
      AuthenticatedAppProductsProductIdRoute,
    AuthenticatedAppProductsIndexRoute: AuthenticatedAppProductsIndexRoute,
  }

const AuthenticatedAppProductsRouteWithChildren =
  AuthenticatedAppProductsRoute._addFileChildren(
    AuthenticatedAppProductsRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppBranchesRoute: typeof AuthenticatedAppBranchesRoute
  AuthenticatedAppProductsRoute: typeof AuthenticatedAppProductsRouteWithChildren
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppUsersRoute: typeof AuthenticatedAppUsersRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppBranchesRoute: AuthenticatedAppBranchesRoute,
  AuthenticatedAppProductsRoute: AuthenticatedAppProductsRouteWithChildren,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppUsersRoute: AuthenticatedAppUsersRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
